# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
    -   id: check-added-large-files
-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.2
    hooks:
    -   id: check-jsonschema
        files: default\.json$
        args: ["--schemafile", "https://json.schemastore.org/renovate"]
